"""Data-source configuration status — for the Data Sources / Transparency page.

Reports only WHETHER a given provider's credentials are configured, never
the credential values themselves. This lets the frontend accurately show
"live" vs "demo/unconfigured" for each provider without any secret leaking
into a response body.
"""

from typing import Annotated

from app.api.deps import CurrentUser, get_db
from app.core.config import settings
from app.schemas.base import APIResponse, BaseSchema
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter(prefix="/system", tags=["System / Transparency"])


class ProviderStatus(BaseSchema):
    configured: bool
    note: str


class DataSourcesStatusResponse(BaseSchema):
    air_quality: ProviderStatus
    weather: ProviderStatus
    satellite_fire: ProviderStatus
    satellite_imagery: ProviderStatus
    traffic: ProviderStatus
    database_engine: str


@router.get("/data-sources", response_model=APIResponse[DataSourcesStatusResponse])
async def get_data_sources_status(
    current_user: CurrentUser,
    session: Annotated[AsyncSession, Depends(get_db)],
) -> APIResponse[DataSourcesStatusResponse]:
    """Report which external data providers are actively configured.

    This never returns key/secret values — only booleans and static notes.
    """
    openaq_configured = bool(settings.OPENAQ_API_KEY)
    firms_configured = bool(settings.NASA_FIRMS_MAP_KEY)
    sentinel_configured = bool(
        settings.SENTINEL_HUB_CLIENT_ID and settings.SENTINEL_HUB_CLIENT_SECRET
    )

    return APIResponse(
        data=DataSourcesStatusResponse(
            air_quality=ProviderStatus(
                configured=openaq_configured,
                note=(
                    "OpenAQ API key detected — live ground-station readings "
                    "used where available, with synthetic fallback per-station."
                    if openaq_configured
                    else "No OpenAQ API key configured — all AQI readings are "
                    "generated by the statistical fallback model, clearly "
                    "flagged as synthetic."
                ),
            ),
            weather=ProviderStatus(
                configured=True,  # Open-Meteo requires no API key
                note=(
                    "Open-Meteo is polled every 30 minutes but its response is "
                    "not yet persisted into AQI readings. The temperature/"
                    "humidity/wind values attached to each reading currently "
                    "come from OpenAQ (when available) or the synthetic "
                    "fallback model, not from this Open-Meteo call."
                ),
            ),
            satellite_fire=ProviderStatus(
                configured=firms_configured,
                note=(
                    "NASA FIRMS active-fire data available."
                    if firms_configured
                    else "NASA FIRMS map key not configured — fire/biomass "
                    "burning signals are unavailable."
                ),
            ),
            satellite_imagery=ProviderStatus(
                configured=sentinel_configured,
                note=(
                    "Sentinel Hub credentials detected — satellite imagery "
                    "features available."
                    if sentinel_configured
                    else "Sentinel Hub credentials not configured — satellite "
                    "imagery features are unavailable."
                ),
            ),
            traffic=ProviderStatus(
                configured=False,
                note=(
                    "No pluggable traffic provider is wired into the backend. "
                    "Traffic influence on AQI and forecasts is a synthetic "
                    "time-of-day multiplier (morning/evening peak factors) "
                    "built directly into the ingestion and forecast pipelines. "
                    "No paid traffic API is used or required."
                ),
            ),
            database_engine="PostgreSQL + PostGIS (spatial queries) + TimescaleDB (time-series compression/continuous aggregates on aqi_readings)",
        )
    )
